### ISSUE TITLE
Grails 3.2.4: multiple Datasources "No Session found for current thread" exception when accessing secondary datasource

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#10383]
I've followed the instructions reported on point "4.4.5 Multiple Datasources" of http://docs.grails.org/latest/guide/single.html#configGORM.

This is the datasource section of my application.yml

--------------------------------------------------
```

dataSources:
  dataSource:
      #dbCreate: create-drop
      #url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: com.mysql.cj.jdbc.Driver
      pooled: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      url: **********

      username: **********
      password: **********

      logSql: true

      properties:
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: true
        validationQuery: SELECT 1 as dbcp_connection_test

  dataSource2:
      #dbCreate: create-drop
      #url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: com.mysql.cj.jdbc.Driver
      pooled: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      url: **********

      username: **********
      password: **********

      logSql: true

      properties:
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: true
        validationQuery: SELECT 1 as dbcp_connection_test


```
--------------------------------------------------

These are my domain classes

--------------------------------------------------
```

package multidb3

class User {
  Long id

  String name
  String lastname

  static constraints = {
  }

  static mapping = {
    version false
  }
}

```
--------------------------------------------------
```

package multidb3

class Message {
  Long id

  String subject
  String body

  static constraints = {
  }

  static mapping = {
    datasource 'dataSource2'

    version false
  }
}

```
--------------------------------------------------

Message is a table in secondary datasource (dataSource2)

When I try to access Message for example 

 List<Message> messages = Message.list()

I get the exception:

Class: org.hibernate.HibernateException
Message: null
Caused by: No Session found for current thread

I've attached an example application, see TestController->index

### Environment Information
- **Operating System**: Linux Mint 18.1 64 bit
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_111
- **Container Version (If Applicable):**

[multidb3.zip](https://github.com/grails/grails-core/files/677341/multidb3.zip)

**Comment by atasc** [comment]
Please refer to this new example application. It uses a H2 db so it is simpler to run.

[multidb31.zip](https://github.com/grails/grails-core/files/691475/multidb31.zip)

**Comment by zyro23** [comment]
comparing the gorm-5 `HibernateDatastoreSpringInitializer` with the gorm-6 one, it looks like the gorm-6 `OpenSessionInViewInterceptor` is not multi-datasource aware anymore? why?

* https://github.com/grails/grails-data-mapping/blob/v5.0.12/grails-datastore-gorm-hibernate5/src/main/groovy/grails/orm/bootstrap/HibernateDatastoreSpringInitializer.groovy#L314
* https://github.com/grails/gorm-hibernate5/blob/v6.0.5/grails-datastore-gorm-hibernate5/src/main/groovy/grails/orm/bootstrap/HibernateDatastoreSpringInitializer.groovy#L190

**Comment by graemerocher** [comment]
Because it is wasteful to open a connection for every request for every data source and it doesn't scale, so it isn't a sensible default.

**Comment by graemerocher** [comment]
Something like that yes, the interceptors are picked up automatically.

**Comment by atasc** [comment]
Sorry but it is not clear how to use a secondary data source. I need to use it in a controller, could you please be more clear?
Documentation says only to set application.yml.

**Comment by graemerocher** [comment]
Use either `withSession` or `withTransaction` for the scope of the method in the controller

**Comment by borgiani** [comment]
@graemerocher but is there a way to enable OSIV for a second datasource?
I've tried something on the lines of what @zyro23 said, but didn't really work.
I understand the point of being wasteful opening a connection for every request, but I rely strongly on two databases, and having to manually handle sessions with `withSession` and `withTransaction` is adding a huge overhead in development. Enabling OSIV for my second datasource would save us a lot of effort, and I'd more than happily take that trade-off.

**Comment by zyro23** [comment]
our current approach:

put all persistence logic into a `@Transactional` services. or use gorm data services.

grails-3.2.4 will use the `ChainedTransactionManager` by default, so all `DataSource`s will have their sessions opened "inside" the transactional methods.

important is that if your dataSource is configured `readOnly = true`, you have to configure it `transactional = true` to include it in the `ChainedTransactionManager`.

if you need the open sessions for not hitting `LazyLoadingException`s (e.g. caused by iterating over associations in a view), i suggest you check this hibernate setting:

`hibernate.enable_lazy_load_no_trans: true`

(ref. https://jira.spring.io/browse/SPR-12823?focusedCommentId=113801&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-113801)

**Comment by borgiani** [comment]
I didn't know `enable_lazy_load_no_trans`, that did the trick, thanks!

**Comment by ch0wnag3** [comment]
@zyro23 I am still experiencing this issue on Grails 3.3.1 even after putting persistence logic for my secondary data source in a `@Transactional` service.

Can you please confirm if there are any other steps necessary? Please note that I have already done the following:

* Set the `datasource` property within the static `mapping` section of my domain class
* Set the static `datasource` property on my service class

**Comment by zyro23** [comment]
try `grails.gorm.transactions.Transactional(connection = "mySecondDataSourceName")`.

**Comment by borgiani** [comment]
I'm still having issues with this on 3.3.1.
Standard @Transactional service is getting me `No session found for current thread` when I access a domain class from the second datasource.
Using `Transactional(connection = 'secondDSName') doesn't do the trick either, as my service needs to access domain classes from both data sources.
Any ideas?
The only way I can get this to work is by adding `withTransaction` manually.

**Comment by zyro23** [comment]
check the changes reg. the `ChainedTransactionManagerPostProcessor` (disabled by default since 3.3.0): http://docs.grails.org/3.3.0/guide/upgrading.html and try re-enabling via `application.yml`..
```
grails:
  transaction:
    chainedTransactionManagerPostProcessor:
      enabled: true
```
with that config, omitting the `connection` attribute should work (or rather not make a difference).

but make sure you understand the implications of chained transaction handling, i.e. the best-effort two-phase commit ("be2pc") approach.

**Comment by ch0wnag3** [comment]
Thank you for the response, @zyro23. I did try setting the `connection` attribute on my `@Transactional` annotation but it had no effect.

I did see that bit about the `ChainedTransactionManagerPostProcessor` configuration in the 3.3.0 upgrade guide but that also had no effect. I'm still getting the exception.

My experience is the same as @borgiani in that using the `withTransaction` block is the only thing that seems to make it work.

**Comment by borgiani** [comment]
Yup, same here.

**Comment by zyro23** [comment]
i just pushed a sample app showing that multi dataSource handling works.

there are quite a few moving parts in that commit. most importantly, note that the `OpenSessionInViewInterceptor` defined in the `PersistenceConfig` is only required because the default static scaffolding templates require an open session.

if you run the sample without the scaffolding controller for `ds2`, you can as well delete the `PersistenceConfig`. i added the controllers just to be able to verify the results in the web ui easily.

this shows that the assertions in `MyService` involving domain classes mapped to different/multiple dataSources work.

hth, zyro

**Comment by ch0wnag3** [comment]
Thank you very much for your example app, @zyro23, but unfortunately, I was still unable to get my secondary data source working.

I've created my own sample app and recreated the issue using a file-based H2 database. I'm hoping you can easily identify where I've gone wrong.

**Comment by davidbairdala** [comment]
I am experiencing this problem as well. I have try re-enabling the ChainedTransactionManagerPostProcessor, and have marked all my service methods as transactional. If I wrap my service calls in Domain.withNewSession { } they work, otherwise I get "no session found for current thread". We have three different data sources configured.

I will try the OSIV interceptor and see if that makes a difference

**Comment by zyro23** [comment]
so i was able to reproduce two different issues reg. the chained transaction handling.

* #10823
* #10824

and of course, if the `ChainedTransactionManager` does not get configured, it explains "no session found for current thread" for dataSource no. 2...

i think it makes sense to continue the discussion there. thanks for your feedback!

**Comment by ch0wnag3** [comment]
Thanks for the update, @zyro23. It's bittersweet news that there's still a confirmed issue - bad that there's a problem, but I'm glad I'm not crazy. I was beginning to think as much after trying every proposed solution I could find and still hitting exceptions.

I'll keep monitoring this issue and the ones you mentioned in hopes that a solution or workaround is found. I'm not counting using the `withTransaction` block as either since doing that in all my application code would be a massive pain.

**Comment by CHAAAAA** [comment]
Is this issue solved? I am experiencing this problem as well on Grails 3.3.5

**Comment by kranthiboinpally** [comment]
I am currently using grails 3.3.9 version, I am facing similar issue for multi-data source , I tried with ChainedTransactionManager  configuration, but it is not woring.
what would be the workaround without using withTransaction block.

**Comment by kranthiboinpally** [comment]
> I didn't know `enable_lazy_load_no_trans`, that did the trick, thanks!

enable_lazy_load_no_trans is working for you? it is not working for me. could you let me know what is the configuration settings.

**Comment by borgiani** [comment]
@kranthiboinpally it is... partially
I configured it for the secondary datasource:
```yaml
dataSources:
    source2:
        hibernate:
            enable_lazy_load_no_trans: true
```

When I need to load an object from this secondary data source, I still need to do it inside a `withTransaction` block, but once it's loaded, I don't have to keep doing that to load collections from that object (which come as proxies)
So I'm not avoiding having to manually request a transaction, but at least I don't have to keep doing that any time I want to access a lazy attribute from a given object

**Comment by leleFc** [comment]
Any update? I'm in trouble with the same issue (No Session found for current thread)..
I'm trying to upgrade my multi-db  application from grails 3.1 to grails 3.3, the application has a common datasource (the default one with a specific structure) where configurations and users are stored, and many others datasources with specific data but same database structure (different from the default one) for each company.
The application choose the right user datasource by selecting its own inside the common database in a way like that:

MyDomain."$userUtils.retriveDatasourceName()".list()

(userUtil.retrieve DatasourceName() is a method which returns the datasource name associated to the authenticated user from the common database)

But now seems impossible to do the same thing and it's not possible to bind every data access with "MyDomain.withNewTransaction{}"

**Comment by ruiyang** [comment]
Having withTransaction everywhere in the code base is a huge overhead. This is the biggest issue for me with grails. I'll just juse spring boot directly and never use grails again.
But for the legacy app, I still need to maintain it. Looking at the withTransaction scattered in our code base, I feel very sick of it. Multi-datasource shouldn't be a feature from the begining.

**Comment by jkang527** [comment]
I apologize for bringing this backup but in desperate need of some help.
I'm maintaining a legacy app running at 3.3.1, with multiple datasources,
I tried almost everything mentioned above except the withTransactions part (which I want to avoid if possible), and I still could not get it to work.
Basically we have multiple select dropdowns that's populating its options through the GORM data services list() from another domain class- like g:select from=${Books.list()} and all of them are erroring out with the dreaded no session found error.
I think wrapping w withTransactions is the only option left, but i'm not even sure how to go about it using the list method in the generated interface.  Any tips would be very much appreciated.
