### ISSUE TITLE
react profile creates app with missing gormVersion setting

### ISSUE THREAD

**Issue by ggascoigne** [grails/grails-core#10536]
create a new app using the react profile

```bash
$ grails create-app ReactTest2 --profile react
```

and then trying to build it:

```bash
$ ./gradlew server:bootRun

FAILURE: Build failed with an exception.

* Where:
Build file './server/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating project ':server'.
> Could not get unknown property 'gormVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.721 secs
```

When I create an app using the default profile I get a `gradle.properties` that defines:

```
grailsVersion=3.2.7
gormVersion=6.0.9.RELEASE
gradleWrapperVersion=3.4.1
```

however when using the react app I get

```
grailsVersion=3.2.1
gradleWrapperVersion=3.1
```

If I add `gormVersion=6.0.9.RELEASE` it then I can get the build working.  Note that even though I used grails 3.2.7 to create the react app it still lists the grails version as being 3.2.1 in the gradle.properties file.  That's not a typo.

**Comment by graemerocher** [comment]
Fixed in version 2.0.2 of the profile https://github.com/grails-profiles/react/commit/75ee329ea4e6599a8e026d8cb099bb174d1d7ba8

**Comment by danielritter** [comment]
The same error occures in the angular2 profile.

**Comment by ggascoigne** [comment]
How do you get this version of the profile, it's still broken in grails 3.2.8.

How do you find out what version of a profile you are using, I expected that `grails profile-info react` would have listed out the version as well as the other help.
