### ISSUE TITLE
newly created apps with grails 3.2.1? no bueno with gradle 4.0 

### ISSUE THREAD

**Issue by txpokey** [grails/grails-core#10704]
i upgraded to gradle 4.0 AND then created a new grails 3.2.11 application from scratch, and the context will not come up. 

### Steps to Reproduce

1. upgrade to gradle 4.0, of course using the groovy, java, & grails versions quoted below
2. start with clean directory and run:
> grails create-app foo 
> cd foo
> grails run-app 

### Expected Behaviour

you should be able to see the context build and arise. It builds, but will not come up. 

### Actual Behaviour

The message you see is:

>Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled 
> to be removed in Gradle 5.0
>	at build_btnt31xhg7djj6hrso0k1opqn.run(/home/mak/var/work/project/punisher/foo/build.gradle:19)
>The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
>	at build_btnt31xhg7djj6hrso0k1opqn.run(/home/mak/var/work/project/punisher/foo/build.gradle:19)
>
>| Running application...
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':findMainClass'.
>> Illegal null value provided in this collection: [null]

### Environment Information

- **Operating System**: Linux Mint 18 Cinnamon 64-bit
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_131
- **groovy Version:** 2.4.11
- **Container Version (If Applicable):** n/a

### Example Application

- n/a

**Comment by txpokey** [comment]
I should add that I DONT run bash(1), I run ksh(1). This is only significant because testing for the regression was impeded by grails(1) ignoring the GRADLE_HOME environment variable when I ran from ksh(1). I coerced my path to pick up the exact versions of gradle et al and not count on the .sdkman "current" link, which normally works great for me...

**Comment by graemerocher** [comment]
This is resolved in Grails 3.3.0.RC1

**Comment by txpokey** [comment]
confirmed. Thanks!!!

**Comment by dekay2323** [comment]
I am still getting this on an existing project. Grails 3.3.0.RC1 and Gradle 4.0. It started happening on Gradle 3
