### ISSUE TITLE
Compile error with logback.groovy and multi-module build

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#11476]
Running in the 4.0.x branch (currently 4.0.2.BUILD-SNAPSHOT).

During the compile phase, I'm getting this error to the console (it doesn't actually fail the build):
```Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.encoder.PatternLayoutEncoder
 @ line -1, column -1.
Script1.groovy: 6: unable to resolve class ch.qos.logback.classic.filter.ThresholdFilter
 @ line 6, column 1.
   import ch.qos.logback.classic.filter.ThresholdFilter
   ^

Script1.groovy: 5: unable to resolve class ch.qos.logback.classic.PatternLayout
 @ line 5, column 1.
   import ch.qos.logback.classic.PatternLayout
   ^

Script1.groovy: 8: unable to resolve class de.appelgriepsch.logback.GelfAppender
 @ line 8, column 1.
   import de.appelgriepsch.logback.GelfAppender
   ^

Script1.groovy: 9: unable to resolve class grails.util.BuildSettings
 @ line 9, column 1.
   import grails.util.BuildSettings
   ^

Script1.groovy: 11: unable to resolve class grails.util.Metadata
 @ line 11, column 1.
   import grails.util.Metadata
   ^

Script1.groovy: 10: unable to resolve class grails.util.Environment
 @ line 10, column 1.
   import grails.util.Environment
   ^

Script1.groovy: 12: unable to resolve class org.springframework.boot.logging.logback.ColorConverter
 @ line 12, column 1.
   import org.springframework.boot.logging.logback.ColorConverter
   ^

Script1.groovy: 4: unable to resolve class ch.qos.logback.classic.Level
 @ line 4, column 1.
   import ch.qos.logback.classic.Level
   ^

Script1.groovy: 7: unable to resolve class ch.qos.logback.core.util.FileSize
 @ line 7, column 1.
   import ch.qos.logback.core.util.FileSize
   ^

Script1.groovy: 13: unable to resolve class org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter
 @ line 13, column 1.
   import org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter
   ^

Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
Script1.groovy: -1: unable to resolve class ch.qos.logback.classic.Level
 @ line -1, column -1.
20 errors

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:980)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:647)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:596)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
        at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
        at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
        at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:540)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:552)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:588)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:579)
        at groovy.lang.GroovyShell$parse.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:71)
        at ch.qos.logback.classic.gaffer.GafferConfigurator$run.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:44)
        at ch.qos.logback.classic.gaffer.GafferUtil.runGafferConfiguratorOn(GafferUtil.java:43)
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:67)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at grails.util.Environment.<clinit>(Environment.java:64)
        at org.grails.core.artefact.DomainClassArtefactHandler.<clinit>(DomainClassArtefactHandler.java:56)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1732)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1556)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:1042)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.newInstance(DefaultGroovyMethods.java:17142)
        at org.grails.core.io.support.GrailsFactoriesLoader.loadFactoriesWithArguments(GrailsFactoriesLoader.groovy:65)
        at org.grails.core.io.support.GrailsFactoriesLoader.loadFactories(GrailsFactoriesLoader.groovy:47)
        at org.grails.compiler.injection.GlobalGrailsClassInjectorTransformation.visit(GlobalGrailsClassInjectorTransformation.groovy:57)
        at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:318)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:965)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:647)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:623)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:268)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:68)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:87)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:75)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:113)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:46)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:36)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:36)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.execute(IsolatedClassloaderWorker.java:54)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
```

It looks like it's caused by the addition of `@Slf4j` to https://github.com/grails/grails-core/blob/cd750f743d89fc528980e822d722ab5ab7e8e649/grails-bootstrap/src/main/groovy/grails/util/Environment.java

I believe it's causing the logback.groovy file to try to be loaded too early in the build process.

I'm trying to reproduce it in a sample application, but having trouble getting it to happen.

I have confirmed removing the LoggerFactory from Environment.java fixes the issue.

**Comment by longwa** [comment]
Looks like the `DomainClassArtefactHandler` has an unused reference:
```
private static boolean developmentMode = Environment.isDevelopmentMode();
```
This is what's trigger the creation of the Environment class during the build. One of the AST transformations is causing the DCAH to be loaded.

**Comment by longwa** [comment]
I can't find the combination of annotations or whatever that is causing it in a small sample application, but it's pretty clear from the stack that it's trying to initialize logback now in an AST transformation that is using `Environment`.

I think using the SLF4J logger factory in a class that can be used during compilation is probably a bad idea anyway even though I think we can safely remove the reference from the DomainClassArtefactHandler that's referencing it.

**Comment by longwa** [comment]
Ok, I figured out how to reproduce it.

You need to have a mult-project build and have a logback.groovy in a submodule that is exposed to all of the applications.

I think in a single project build it might be excluded.

https://github.com/longwa/logbackError

**Comment by jameskleeh** [comment]
@longwa Does it resolve the issue to just remove the reference from DCAH?

**Comment by longwa** [comment]
@jameskleeh No, it just moves the failure to a slightly later point in the compile. It will fail initializing the Environment here:

https://github.com/grails/grails-core/blob/6110534c29cde2f820be3bb35991bb153a814a93/grails-web-boot/src/main/groovy/org/grails/compiler/boot/BootInitializerClassInjector.groovy#L82

It seemed fine to remove it from the DCAH anyway since it was private and unused.

**Comment by longwa** [comment]
This problem is back with 5.0.0.RC1

**Comment by augustl** [comment]
Should be fixed in the upcoming 5.1.2: https://github.com/grails/grails-core/issues/12291

**Comment by xpusostomos** [comment]
Errm, I'm using grails 5.3.3 and I'm still seeing the error.
