### ISSUE TITLE
Unable to resolve dependencies -- https://repo.grails.org/grails/core returns 404

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#11825]
Go to [start.grails.org](https://start.grails.org), download an app. 

Unzip it and run `./gradlew help`

```
 ./gradlew help       

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'myapp-2'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.grails:grails-gradle-plugin:4.0.10.
     Searched in the following locations:
       - https://repo.grails.org/grails/core/org/grails/grails-gradle-plugin/4.0.10/grails-gradle-plugin-4.0.10.pom
       - https://repo.grails.org/grails/core/org/grails/grails-gradle-plugin/4.0.10/grails-gradle-plugin-4.0.10.jar
     Required by:
         project :
   > Could not find gradle.plugin.com.github.erdi.webdriver-binaries:webdriver-binaries-gradle-plugin:2.0.
     Searched in the following locations:
       - https://repo.grails.org/grails/core/gradle/plugin/com/github/erdi/webdriver-binaries/webdriver-binaries-gradle-plugin/2.0/webdriver-binaries-gradle-plugin-2.0.pom
       - https://repo.grails.org/grails/core/gradle/plugin/com/github/erdi/webdriver-binaries/webdriver-binaries-gradle-plugin/2.0/webdriver-binaries-gradle-plugin-2.0.jar
     Required by:
         project :
   > Could not find org.grails.plugins:hibernate5:7.0.4.
     Searched in the following locations:
       - https://repo.grails.org/grails/core/org/grails/plugins/hibernate5/7.0.4/hibernate5-7.0.4.pom
       - https://repo.grails.org/grails/core/org/grails/plugins/hibernate5/7.0.4/hibernate5-7.0.4.jar
     Required by:
         project :
   > Could not find com.bertramlabs.plugins:asset-pipeline-gradle:3.2.4.
     Searched in the following locations:
       - https://repo.grails.org/grails/core/com/bertramlabs/plugins/asset-pipeline-gradle/3.2.4/asset-pipeline-gradle-3.2.4.pom
       - https://repo.grails.org/grails/core/com/bertramlabs/plugins/asset-pipeline-gradle/3.2.4/asset-pipeline-gradle-3.2.4.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by haaah** [comment]
Facing same issue when created a new Grails App with vue profile and try to run up

`
A problem occurred configuring project ':server'.
> Could not resolve all artifacts for configuration ':server:classpath'.
   > Could not find grails-gradle-plugin.jar (org.grails:grails-gradle-plugin:4.0.10).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/grails/grails-gradle-plugin/4.0.10/grails-gradle-plugin-4.0.10.jar
   > Could not find grails-shell.jar (org.grails:grails-shell:4.0.10).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/grails/grails-shell/4.0.10/grails-shell-4.0.10.jar
   > Could not find grails-gradle-model.jar (org.grails:grails-gradle-model:4.0.10).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/grails/grails-gradle-model/4.0.10/grails-gradle-model-4.0.10.jar
   > Could not find groovy-ant.jar (org.codehaus.groovy:groovy-ant:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-ant/2.5.14/groovy-ant-2.5.14.jar
   > Could not find groovy-json.jar (org.codehaus.groovy:groovy-json:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-json/2.5.14/groovy-json-2.5.14.jar
   > Could not find groovy-jmx.jar (org.codehaus.groovy:groovy-jmx:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-jmx/2.5.14/groovy-jmx-2.5.14.jar
   > Could not find grails-bootstrap.jar (org.grails:grails-bootstrap:4.0.10).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/grails/grails-bootstrap/4.0.10/grails-bootstrap-4.0.10.jar
   > Could not find groovy-templates.jar (org.codehaus.groovy:groovy-templates:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-templates/2.5.14/groovy-templates-2.5.14.jar
   > Could not find groovy-xml.jar (org.codehaus.groovy:groovy-xml:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-xml/2.5.14/groovy-xml-2.5.14.jar
   > Could not find groovy.jar (org.codehaus.groovy:groovy:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy/2.5.14/groovy-2.5.14.jar
   > Could not find spring-boot-gradle-plugin.jar (org.springframework.boot:spring-boot-gradle-plugin:2.1.18.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/springframework/boot/spring-boot-gradle-plugin/2.1.18.RELEASE/spring-boot-gradle-plugin-2.1.18.RELEASE.jar
   > Could not find gradle-bintray-plugin.jar (com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.5).
     Searched in the following locations:
         https://repo.grails.org/grails/core/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.8.5/gradle-bintray-plugin-1.8.5.jar
   > Could not find dependency-management-plugin.jar (io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/io/spring/gradle/dependency-management-plugin/1.0.11.RELEASE/dependency-management-plugin-1.0.11.RELEASE.jar
   > Could not find ant-junit.jar (org.apache.ant:ant-junit:1.9.15).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/apache/ant/ant-junit/1.9.15/ant-junit-1.9.15.jar
   > Could not find ant.jar (org.apache.ant:ant:1.9.15).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/apache/ant/ant/1.9.15/ant-1.9.15.jar
   > Could not find spring-boot-cli.jar (org.springframework.boot:spring-boot-cli:2.1.18.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/springframework/boot/spring-boot-cli/2.1.18.RELEASE/spring-boot-cli-2.1.18.RELEASE.jar
   > Could not find snakeyaml.jar (org.yaml:snakeyaml:1.28).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar
   > Could not find spring-boot-loader-tools.jar (org.springframework.boot:spring-boot-loader-tools:2.1.18.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/springframework/boot/spring-boot-loader-tools/2.1.18.RELEASE/spring-boot-loader-tools-2.1.18.RELEASE.jar
   > Could not find spring-core.jar (org.springframework:spring-core:5.1.19.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/springframework/spring-core/5.1.19.RELEASE/spring-core-5.1.19.RELEASE.jar
   > Could not find ant-launcher.jar (org.apache.ant:ant-launcher:1.9.15).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/apache/ant/ant-launcher/1.9.15/ant-launcher-1.9.15.jar
   > Could not find groovy-groovydoc.jar (org.codehaus.groovy:groovy-groovydoc:2.5.14).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-groovydoc/2.5.14/groovy-groovydoc-2.5.14.jar
   > Could not find ant-antlr.jar (org.apache.ant:ant-antlr:1.9.15).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/apache/ant/ant-antlr/1.9.15/ant-antlr-1.9.15.jar
   > Could not find spring-security-crypto.jar (org.springframework.security:spring-security-crypto:5.1.13.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/springframework/security/spring-security-crypto/5.1.13.RELEASE/spring-security-crypto-5.1.13.RELEASE.jar
   > Could not find httpclient.jar (org.apache.httpcomponents:httpclient:4.5.13).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
   > Could not find spring-jcl.jar (org.springframework:spring-jcl:5.1.19.RELEASE).
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/springframework/spring-jcl/5.1.19.RELEASE/spring-jcl-5.1.19.RELEASE.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

**Comment by tbird2** [comment]
grailsCentral (https://repo.grails.org/grails/core) appears to be down. It simply returns:

{
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}

**Comment by puneetbehl** [comment]
It seems like somehow artifactory URL is changed to https://repo.grails.org/artifactory/core

**Comment by aadrian** [comment]
@puneetbehl unfortunately this prevents even basic operations like "help" or just createing a new app from the CLI:

```
grails create-app --help
| Error Error occurred running Grails CLI: Could not find artifact org.grails:grails-bom:pom:4.0.10 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

```

**Comment by Nobhokleng** [comment]
> It seems like somehow artifactory URL is changed to https://repo.grails.org/artifactory/core

Thanks it's working now.

**Comment by m4rc77** [comment]
Existing projects can workaround this issue by setting 
```
repositories {
    mavenLocal()
//    maven { url "https://repo.grails.org/grails/core" } --> see https://github.com/grails/grails-core/issues/11825
    maven { url "https://repo.grails.org/artifactory/core" }
}
``` 
in the `build.gradle` file .... **but i can not guarantee that this is safe/a good idea as i am not a grails contributer!**

**How should new projects workaround this issue? Should they patch the grails installation?**

**Comment by yasokada-lc** [comment]
Workaround cannot be works
grails buldled grailsw hard coded "https://repo.grails.org/grails/core"
https://github.com/grails/grails-wrapper/blob/master/wrapper/src/main/groovy/grails/init/RunCommand.groovy#L28

**Comment by cosenmarco** [comment]
Unfortunately the old URL is hardcoded in the grails wrapper. See 
https://github.com/grails/grails-wrapper/blob/master/starter/src/main/java/grails/init/Start.java

**Comment by JasonTypesCodes** [comment]
@cosenmarco We do not intend for this URL change to be permanent.

We have reached out to JFrog for assistance with this issue.  We'll update here when we have more information.

**Comment by cnrudd** [comment]
@JasonTypesCodes Thank you for looking into this issue.  
Do you have a sense of about how long this URL change will last? before it reverts back to "https://repo.grails.org/grails/core" ?
We are trying to determine whether or not we need to re-release our plugins with the new URL, to avoid blocking users.

**Comment by JasonTypesCodes** [comment]
> Do you have a sense of about how long this URL change will last? before it reverts back to "https://repo.grails.org/grails/core" ?
We do not yet have timeline for resolution.  We'll update here once we do.

**Comment by cosenmarco** [comment]
> @cosenmarco We do not intend for this URL change to be permanent.
> 
> We have reached out to JFrog for assistance with this issue. We'll update here when we have more information.

Alright. I was more for giving the ability to override in case this happens again / one wants to use a caching proxy... I'll be waiting for a resolutions with our pipelines in a broken state...

**Comment by alemedero** [comment]
Can't even run my projects. This is a blocking issue.  Any workaround for existing projects??

Thanks in advance.

**Comment by jeffbrown** [comment]
> Any workaround for existing projects

I believe all of the artifacts should be available at https://repo.grails.org/artifactory/core for now.

**Comment by jrAtAustin** [comment]
@jeffbrown still not able to access some artifacts:

```
    buildscript {
        repositories {
            maven { url "https://repo.grails.org/artifactory/core" }
            maven { url "https://build.shibboleth.net/nexus/content/repositories/releases" }
            maven { url "https://mvnrepository.com/artifact/org.grails.plugins/sentry" }
            maven { url "https://grails.jfrog.io/grails/core" }
            mavenCentral()
            mavenLocal()
            jcenter()
            maven { url "https://repo.grails.org/grails/core" }
        }
        dependencies {
            classpath "org.grails:grails-gradle-plugin:$grailsVersion"
            classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.2.3"
        }
    }
```

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'okta-oauth2-service'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not find org.grails.plugins:spring-security-oauth2:1.2.0.
     Searched in the following locations:
         file:/Users/johnruggentaler/.m2/repository/org/grails/plugins/spring-security-oauth2/1.2.0/spring-security-oauth2-1.2.0.pom
         file:/Users/johnruggentaler/.m2/repository/org/grails/plugins/spring-security-oauth2/1.2.0/spring-security-oauth2-1.2.0.jar
         https://repo.grails.org/grails/core/org/grails/plugins/spring-security-oauth2/1.2.0/spring-security-oauth2-1.2.0.pom
         https://repo.grails.org/grails/core/org/grails/plugins/spring-security-oauth2/1.2.0/spring-security-oauth2-1.2.0.jar
     Required by:
         project :
```

**Comment by jeffbrown** [comment]
@jrAtAustin The dependencies you show there look like app dependencies bu the `repositories` you show there is for your build script dependencies, not the app dependencies.  What repos do you have configured for your app dependencies?

**Comment by jrAtAustin** [comment]
@jeffbrown I was trying to build the Spring Security Oath 2 Okta plugin located here: https://github.com/moksamedia/okta-oauth2-service

Below is build.gradle

```
buildscript {
    repositories {
        maven { url "https://repo.grails.org/artifactory/core" }
        maven { url "https://build.shibboleth.net/nexus/content/repositories/releases" }
        maven { url "https://mvnrepository.com/artifact/org.grails.plugins/sentry" }
        maven { url "https://grails.jfrog.io/grails/core" }
        mavenCentral()
        mavenLocal()
        jcenter()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.2.3"
    }
}

version "0.1"
group "spring.security.oauth2.okta"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"org.grails.grails-plugin"
apply plugin:"org.grails.grails-plugin-publish"
apply plugin:"asset-pipeline"
apply plugin:"org.grails.grails-gsp"

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencies {
    compile 'org.grails.plugins:spring-security-core:3.3.1'
    compile 'org.grails.plugins:spring-security-oauth2:1.2.0'
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-web-boot"
    compile "org.grails:grails-logging"
    compile "org.grails:grails-plugin-rest"
    compile "org.grails:grails-plugin-databinding"
    compile "org.grails:grails-plugin-i18n"
    compile "org.grails:grails-plugin-services"
    compile "org.grails:grails-plugin-url-mappings"
    compile "org.grails:grails-plugin-interceptors"
    compile "org.grails.plugins:cache"
    compile "org.grails.plugins:async"
    compile "org.grails.plugins:scaffolding"
    compile "org.grails.plugins:gsp"
    console "org.grails:grails-console"
    profile "org.grails.profiles:web-plugin"
    provided "org.grails:grails-plugin-services"
    provided "org.grails:grails-plugin-domain-class"
    runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.14.2"
    testCompile "org.grails:grails-gorm-testing-support"
    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails:grails-web-testing-support"
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    addResources = true
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}
// enable if you wish to package this plugin as a standalone application
bootRepackage.enabled = false
grailsPublish {
    // TODO: Provide values here
    user = 'user'
    key = 'key'
    githubSlug = 'foo/bar'
    license {
        name = 'Apache-2.0'
    }
    title = "My Plugin"
    desc = "Full plugin description"
    developers = [johndoe:"John Doe"]
}


assets {
    packagePlugin = true
}
```

**Comment by jrAtAustin** [comment]
Ah, I think I got it. Thanks @jeffbrown and others!

```
repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/artifactory/core" }
    maven { url "https://repo.grails.org/grails/core" }
}
```

**Comment by kfujita-cohere** [comment]
We also hit some issues today with the grails-wrapper in our CI builds. made the changes to our gradle file to get everything to work locally

**Comment by kfujita-cohere** [comment]
We also had some failures with our CI today and had to make some change outside of the gradle file. We ended up forking [grails-wrapper](https://github.com/grails/grails-wrapper) and updating the urls: [here](https://github.com/grails/grails-wrapper/blob/master/starter/src/main/java/grails/init/Start.java#L22) (also replacing `http` with `https`), [here](https://github.com/grails/grails-wrapper/blob/master/wrapper/src/main/groovy/grails/init/RunCommand.groovy#L28), [here](https://github.com/grails/grails-wrapper/blob/master/wrapper/build.gradle#L7), [here](https://github.com/grails/grails-wrapper/blob/master/wrapper/build.gradle#L51), [here](https://github.com/grails/grails-wrapper/blob/master/publishing/grailsCentralPublishing.gradle#L41), and [here](https://github.com/grails/grails-wrapper/blob/master/publishing/grailsCentralPublishing.gradle#L46).

We then ran [the travis-build.sh](https://github.com/grails/grails-wrapper/blob/master/travis-build.sh) and took the jar file from `wrapper/build/libs`. We copied that over to our root directory and replaced our `grails-wrapper.jar` temporarily.

Hopefully this is ok to post here for those experiencing issues beyond the local url change workaround.

**Comment by martin-walsh** [comment]
Affects legacy apps also. Grails 2 plugins are missing. `tomcat`, `csv`, `spring-security-core` etc.

Is there a workaround for Grails 2 apps?

```

==== grailsCentral: tried
--
&nbsp; | http://repo.grails.org/grails/plugins/org/grails/plugins/tomcat/8.0.50/tomcat-8.0.50.pom
&nbsp; | -- artifact org.grails.plugins#tomcat;8.0.50!tomcat.zip:
&nbsp; | http://repo.grails.org/grails/plugins/org/grails/plugins/tomcat/8.0.50/tomcat-8.0.50.zip

```

**Comment by jeffbrown** [comment]
> Is there a workaround for Grails 2 apps?

Using `https://repo.grails.org/artifactory/core` should work for now.

**Comment by mifans** [comment]
> It seems like somehow artifactory URL is changed to https://repo.grails.org/artifactory/core

it work, thanks

**Comment by martin-walsh** [comment]
Grails 2 workaround seems to be to do:
```
// grailsCentral()
mavenRepo url: 'https://repo.grails.org/artifactory/plugins', name: 'grailsCentral'
```

That overrides the defaults supplied by `org.codehaus.groovy.grails.resolve.config.RepositoriesConfigurer`

**Comment by 10pearls-atifhussain** [comment]
it's better to share the ETA to resolve it so that people can plan their build releases. I hope this alternative URL for an temporary basis.

**Comment by vsachinv** [comment]
Looks like some migration process going on in Jfrog due to upgrade. 
<img width="1012" alt="Screen Shot 2021-06-08 at 3 36 37 PM" src="https://user-images.githubusercontent.com/1142890/121167449-91531b80-c86f-11eb-8bef-8a11568b8ad1.png">

**Comment by jeffbrown** [comment]
> it's better to share the ETA to resolve it so that people can plan their build releases.

We understand.  Unfortunately there is not a lot of information to share.  We are in communication with JFrog.  They have let us know that the problem was caused by a software update.  We are working with them to try and get the repository responding to the formerly supported url patterns.

**Comment by rkimaoui** [comment]
I have same problem:

`
> Could not resolve all files for configuration ':runtime'.
   > Could not find any matches for net.minidev:json-smart:[1.3.1,2.3] as no versions of net.minidev:json-smart are available.
     Searched in the following locations:
       - https://repo.grails.org/grails/core/net/minidev/json-smart/maven-metadata.xml
       - https://repo.grails.org/grails/core/net/minidev/json-smart/
     Required by:
         project : > org.grails.plugins:spring-security-rest:3.0.0.RC1 > com.nimbusds:nimbus-jose-jwt:4.36
Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

**Comment by matthijsbierman** [comment]
@rkimaoui see the suggested workaround here: https://github.com/grails/grails-core/issues/11825#issuecomment-856243525

**Comment by amacleay-cohere** [comment]
@rkimaoui You may want to check out https://github.com/CohereHealth/grails-wrapper#hackety-hack-dont-talk-back - we also needed to replace `grails-wrapper.jar` in our project for it to build and this describes the process we're using while the grails repo standard URL is down/while https://github.com/grails/grails-wrapper/issues/5 is open

**Comment by jeffbrown** [comment]
**Update:** We still have validation to do but the repository is responding successfully to at least some scenarios that were problematic during the outage.  I am not sure the issue if the issue is 100% resolved yet or not, but progress has been made.

**Comment by reddyshyam** [comment]
Looks like URL issues resolved now.

I can access https://repo.grails.org/grails/core/

**Comment by luiszimmermann** [comment]
The issue seems to be partially resolved. With the `$HOME/.grails/wrapper` cache I can run the `./grailsw` locally or in our pipelines and everything works, but when there is no cache and the `grailsw` are runned for the first time I receive this message: 

```
You must be connected to the internet the first time you use the Grails wrapper
org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
```

**Comment by JasonTypesCodes** [comment]
> The issue seems to be partially resolved. With the `$HOME/.grails/wrapper` cache I can run the `./grailsw` locally or in our pipelines and everything works, but when there is no cache and the `grailsw` are runned for the first time I receive this message:
> 
> ```
> You must be connected to the internet the first time you use the Grails wrapper
> org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
> ```

@luiszimmermann Which version of Grails are you running?

**Comment by luiszimmermann** [comment]
> > The issue seems to be partially resolved. With the `$HOME/.grails/wrapper` cache I can run the `./grailsw` locally or in our pipelines and everything works, but when there is no cache and the `grailsw` are runned for the first time I receive this message:
> > ```
> > You must be connected to the internet the first time you use the Grails wrapper
> > org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
> > ```
> 
> @luiszimmermann Which version of Grails are you running?

I can reproduce the same error in Grails `4.0.9` and `3.3.12`.

**Comment by JasonTypesCodes** [comment]
@luiszimmermann I created an issue for that here: https://github.com/grails/grails-wrapper/issues/7

**Comment by danieljoeblack** [comment]
Grails 3 projects are building properly for me but I am still unable to build Grails 2 projects. I'm getting the following when trying to run:

`Error Resolve error obtaining dependencies: Could not transfer artifact xalan:serializer:jar:2.7.1 from/to grailsCentral (http://repo.grails.org/grails/plugins): Permanent Redirect (308)`

One thing I noticed is that 'http://repo.grails.org/grails/plugins' redirects to 'https://repo.grails.org/artifactory/plugins/' when the trailing slash is omitted which it seems to be for Grails 2.

**Comment by JasonTypesCodes** [comment]
@danieljoeblack I've been unable to recreate this in Grails 2.5.6 with standard configuration, but I suspect explicitly using `https://repo.grails.org/grails/plugins/` as your repo will work.

**Comment by danieljoeblack** [comment]
@JasonTypesCodes I'm running 2.3.9 for the record.

When I explicitly set the repo url to `https://repo.grails.org/grails/plugins/` I'm getting: 

`Error Could not transfer artifact org.grails.plugins:tomcat:zip:7.0.53 from/to repo_grails_org_grails_plugins_ (https://repo.grails.org/grails/plugins/): peer not authenticated
`

Changing it to `http://repo.grails.org/grails/plugins/` I get:

'Could not transfer artifact org.grails.plugins:webxml:pom:1.4.1 from/to repo_grails_org_grails_plugins_ (http://repo.grails.org/grails/plugins/): Permanent Redirect (308)
'

Was the repo URL accessible via http before? It seems to force https now...

**Comment by kfujita-cohere** [comment]
@luiszimmermann we were running into this yesterday and this is the workaround that we used https://github.com/grails/grails-core/issues/11825#issuecomment-856250177

**Comment by kfujita-cohere** [comment]
> > The issue seems to be partially resolved. With the `$HOME/.grails/wrapper` cache I can run the `./grailsw` locally or in our pipelines and everything works, but when there is no cache and the `grailsw` are runned for the first time I receive this message:
> > ```
> > You must be connected to the internet the first time you use the Grails wrapper
> > org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
> > ```
> 
> @luiszimmermann Which version of Grails are you running?

@luiszimmermann We were running into this yesterday and this is the workaround we used https://github.com/grails/grails-core/issues/11825#issuecomment-856250177

**Comment by vsachinv** [comment]
@danieljoeblack I have also faced same issue on Grails 2.3.11 as well. It looks more like SSL related in Java7. I have tried things but didn't get it working yet. Did you get any clue?  

> @JasonTypesCodes I'm running 2.3.9 for the record.
> 
> When I explicitly set the repo url to `https://repo.grails.org/grails/plugins/` I'm getting:
> 
> `Error Could not transfer artifact org.grails.plugins:tomcat:zip:7.0.53 from/to repo_grails_org_grails_plugins_ (https://repo.grails.org/grails/plugins/): peer not authenticated `
> 
> Changing it to `http://repo.grails.org/grails/plugins/` I get:
> 
> `Could not transfer artifact org.grails.plugins:webxml:pom:1.4.1 from/to repo_grails_org_grails_plugins_ (http://repo.grails.org/grails/plugins/): Permanent Redirect (308) `
> 
> Was the repo URL accessible via http before? It seems to force https now...

**Comment by icollar** [comment]
FYI - we're now getting 503 from non-artifactory URLs now, and have had to completely remove those references in order to build our apps:

```
15:52:12  #29 467.5 The following artifacts could not be resolved: org.grails.plugins:tomcat:zip:7.0.55.3, org.grails.plugins:codenarc:zip:1.3: Could not transfer artifact org.grails.plugins:tomcat:zip:7.0.55.3 from/to grailsCentral (https://repo.grails.org/grails/plugins): Service Temporarily Unavailable (503)
```

**Comment by JasonTypesCodes** [comment]
The 503s and the 404s that followed were due to an unrelated and unplanned outage and should no longer be occurring.  We are working closely with JFrog on these issues.

**Comment by ShurikAg** [comment]
I am having the same issue with grails 4.0.1
Tried this:
```
repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/artifactory/core" }
        maven { url "https://repo.grails.org/grails/core" }
        mavenCentral()
        jcenter()
    }
```

Does not help.

**Comment by jeffbrown** [comment]
> Works perfectly fine on local, but fails on CI

Is that the wrapper already downloaded locally but not on CI?

**Comment by dwhalloran** [comment]
In Grails 2.4.4 

I am using this:
        mavenRepo "http://repo.grails.org/grails/core"
        mavenRepo "http://repo.grails.org/grails/plugins"

And get this error:
     Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.grails.plugins:rest-client-builder:zip:2.1.1 (Use --stacktrace to see the full trace)

**Comment by ShurikAg** [comment]
> > Works perfectly fine on local, but fails on CI
> 
> Is that the wrapper already downloaded locally but not on CI?

Nope, the wrapper is committed with the code.

**Comment by martin-walsh** [comment]
Will the old `http://` urls be restored (without redirect) or should we make plans to workaround this issue permanently?

**Comment by ShurikAg** [comment]
@jeffbrown now both URL's are not available. So, basically, nothing works. even the workaround.

**Comment by puneetbehl** [comment]
@ShurikAg Thank you, we are aware of some issues with the JFrog artifactory and we are in touch with the JFrog team to help us get the artifactory back online. We will share the further updates as soon as we get them. 

Sorry for the inconvenience.

**Comment by ShurikAg** [comment]
> @ShurikAg Thank you, we are aware of current issues with the JFrog artifactory and we are in touch with the JFrog team to help us get the artifactory back online. We will share the further updates as soon as we get them.
> 
> Sorry for the inconvenience.

Thank you! Is there any workaround for now? Or there is nothing to do?

**Comment by JasonTypesCodes** [comment]
The repository is currently back online.  Thank you everyone for your patience as we are working through these issues.

**Comment by martin-walsh** [comment]
> The repository is currently back online. Thank you everyone for your patience as we work through these issues.

@JasonTypesCodes will the old http urls be restored, or do we need to keep the workarounds for Grails 2.x?

**Comment by JasonTypesCodes** [comment]
> @JasonTypesCodes will the old http urls be restored, or do we need to keep the workarounds for Grails 2.x?

@martin-walsh That is a detail we are still working through.  If the repository does revert back to responding to HTTP requests without a redirect, it will likely be for a limited period to allow a more graceful transition to HTTPS.

What version of Grails 2 are you running, and have you had to take actions beyond adding changing your repositories to `https://repo.grails.org/grails/...`?

**Comment by martin-walsh** [comment]
Running both 2.3.11 & 2.5.4.

Taking no action beyond overriding the definition of `grailsCentral()` in BuildConfig.

The workaround is very simple to apply, but I am wondering if we should plan to apply it permanently as the challenge my organisation faces is 100+ grails projects that need updating.

It is not a deal breaker, just something that needs to be done if `http://` urls aren't coming back

**Comment by JasonTypesCodes** [comment]
> @JasonTypesCodes Running both 2.3.11 & 2.5.4.
> 
> Taking no action beyond overriding the definition of `grailsCentral()` in BuildConfig.
> 
> The workaround is very simple to apply, but I am wondering if we should plan to apply it permanently as the challenge my organisation faces is 100+ grails projects that need updating.
> 
> It is not a deal breaker, just something that needs to be done if `http://` urls aren't coming back

@martin-walsh Thank you, that is good information to have.  

If the HTTP URLs do resume working without a redirect that will be for a limited period.  I would not suggest reverting any updates you have already made to the HTTPS repository URLs.  I would also strongly consider taking the time to update your remaining applications.

**Comment by ShurikAg** [comment]
@jeffbrown @puneetbehl 
I updated the repository URLs, as suggested in the workaround and I am still getting the same issue. Like nothing changed.
Do I need to regenerate the wrapper JAR's somehow to make it work? Or any additional steps to make it work?

Here is my current `build.gradle`

```
buildscript {
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/artifactory/core" }
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "org.grails.plugins:views-gradle:2.0.2"
        classpath "org.grails.plugins:hibernate5:7.0.4"
        classpath 'org.grails.plugins:database-migration:3.1.0.RC1'
    }
}

version "0.2"
group "priz"

// apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"war"
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.plugins.views-json"

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/artifactory/core" }
    maven { url "https://repo.grails.org/grails/core" }
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.12.1'
    }
}

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-plugin-url-mappings"
    compile "org.grails:grails-plugin-rest"
    compile "org.grails:grails-plugin-codecs"
    compile "org.grails:grails-plugin-interceptors"
    compile "org.grails:grails-plugin-services"
    compile "org.grails:grails-plugin-datasource"
    compile "org.grails:grails-plugin-databinding"
    compile "org.grails:grails-web-boot"
    compile "org.grails:grails-logging"
    compile "org.grails.plugins:cache"
    compile "org.grails.plugins:async"
    compile "org.grails.plugins:spring-security-rest:3.0.1"
    compile "org.grails.plugins:views-json"
    compile "org.grails.plugins:views-json-templates"
    compile "org.grails.plugins:events"
    compile "org.grails.plugins:hibernate5"
    compile "org.hibernate:hibernate-core:5.4.18.Final"
    compileOnly "io.micronaut:micronaut-inject-groovy"
    console "org.grails:grails-console"
    profile "org.grails.profiles:rest-api"
    runtime "org.glassfish.web:el-impl:2.1.2-b03"
    runtime "com.h2database:h2"
    runtime "org.apache.tomcat:tomcat-jdbc"
    runtime "javax.xml.bind:jaxb-api:2.3.1"
    testCompile "io.micronaut:micronaut-inject-groovy"
    testCompile "org.grails:grails-gorm-testing-support"
    testCompile "org.mockito:mockito-core"
    testCompile "io.micronaut:micronaut-http-client"
    testCompile "org.grails:grails-web-testing-support"
    testCompile "org.grails:views-json-testing-support"
    testCompile "org.hibernate.validator:hibernate-validator:6.0.20.Final"

    compile "com.amazonaws:aws-java-sdk-s3"

    compile "org.grails.plugins:postgresql-extensions:7.0.0"
    compile "org.postgresql:postgresql:42.2.20"
    compile 'org.grails.plugins:database-migration:3.1.0.RC1'
    compile 'org.liquibase:liquibase-core:3.6.1'

    compile "com.auth0:auth0:1.31.0"
    compile "com.auth0:jwks-rsa:0.18.0"

    compile 'com.papertrailapp:logback-syslog4j:1.0.0'
    compile "com.stripe:stripe-java:20.56.0"

    compile "com.sendinblue:sib-api-v3-sdk:5.2.0"

    runtime "org.grails.plugins:async:4.0.0"
    compile "org.grails:grails-datastore-gorm-async"

    implementation "com.squareup.okhttp3:okhttp:4.9.0"
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.72'

}

bootRun {
    ignoreExitValue true
    jvmArgs(
            '-Dspring.output.ansi.enabled=always',
            '-noverify',
            '-XX:TieredStopAtLevel=1',
            '-Xmx1024m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

sourceSets {
    main {
        resources {
            srcDir 'grails-app/migrations'
        }
    }
}
```

And the error is:
![image](https://user-images.githubusercontent.com/916432/121945098-12bd1900-cd5c-11eb-8c38-ea477789170d.png)

**Comment by kfujita-cohere** [comment]
> @jeffbrown @puneetbehl
> I updated the repository URLs, as suggested in the workaround and I am still getting the same issue. Like nothing changed.
> Do I need to regenerate the wrapper JAR's somehow to make it work? Or any additional steps to make it work?
> 
> Here is my current `build.gradle`
> 
> ```
> buildscript {
>     repositories {
>         mavenLocal()
>         maven { url "https://repo.grails.org/artifactory/core" }
>         maven { url "https://repo.grails.org/grails/core" }
>     }
>     dependencies {
>         classpath "org.grails:grails-gradle-plugin:$grailsVersion"
>         classpath "org.grails.plugins:views-gradle:2.0.2"
>         classpath "org.grails.plugins:hibernate5:7.0.4"
>         classpath 'org.grails.plugins:database-migration:3.1.0.RC1'
>     }
> }
> 
> version "0.2"
> group "priz"
> 
> // apply plugin:"eclipse"
> apply plugin:"idea"
> apply plugin:"war"
> apply plugin:"org.grails.grails-web"
> apply plugin:"org.grails.plugins.views-json"
> 
> repositories {
>     mavenLocal()
>     maven { url "https://repo.grails.org/artifactory/core" }
>     maven { url "https://repo.grails.org/grails/core" }
> }
> 
> configurations {
>     developmentOnly
>     runtimeClasspath {
>         extendsFrom developmentOnly
>     }
> }
> 
> dependencyManagement {
>     imports {
>         mavenBom 'com.amazonaws:aws-java-sdk-bom:1.12.1'
>     }
> }
> 
> dependencies {
>     developmentOnly("org.springframework.boot:spring-boot-devtools")
>     compile "org.springframework.boot:spring-boot-starter-logging"
>     compile "org.springframework.boot:spring-boot-autoconfigure"
>     compile "org.grails:grails-core"
>     compile "org.springframework.boot:spring-boot-starter-actuator"
>     compile "org.springframework.boot:spring-boot-starter-tomcat"
>     compile "org.grails:grails-plugin-url-mappings"
>     compile "org.grails:grails-plugin-rest"
>     compile "org.grails:grails-plugin-codecs"
>     compile "org.grails:grails-plugin-interceptors"
>     compile "org.grails:grails-plugin-services"
>     compile "org.grails:grails-plugin-datasource"
>     compile "org.grails:grails-plugin-databinding"
>     compile "org.grails:grails-web-boot"
>     compile "org.grails:grails-logging"
>     compile "org.grails.plugins:cache"
>     compile "org.grails.plugins:async"
>     compile "org.grails.plugins:spring-security-rest:3.0.1"
>     compile "org.grails.plugins:views-json"
>     compile "org.grails.plugins:views-json-templates"
>     compile "org.grails.plugins:events"
>     compile "org.grails.plugins:hibernate5"
>     compile "org.hibernate:hibernate-core:5.4.18.Final"
>     compileOnly "io.micronaut:micronaut-inject-groovy"
>     console "org.grails:grails-console"
>     profile "org.grails.profiles:rest-api"
>     runtime "org.glassfish.web:el-impl:2.1.2-b03"
>     runtime "com.h2database:h2"
>     runtime "org.apache.tomcat:tomcat-jdbc"
>     runtime "javax.xml.bind:jaxb-api:2.3.1"
>     testCompile "io.micronaut:micronaut-inject-groovy"
>     testCompile "org.grails:grails-gorm-testing-support"
>     testCompile "org.mockito:mockito-core"
>     testCompile "io.micronaut:micronaut-http-client"
>     testCompile "org.grails:grails-web-testing-support"
>     testCompile "org.grails:views-json-testing-support"
>     testCompile "org.hibernate.validator:hibernate-validator:6.0.20.Final"
> 
>     compile "com.amazonaws:aws-java-sdk-s3"
> 
>     compile "org.grails.plugins:postgresql-extensions:7.0.0"
>     compile "org.postgresql:postgresql:42.2.20"
>     compile 'org.grails.plugins:database-migration:3.1.0.RC1'
>     compile 'org.liquibase:liquibase-core:3.6.1'
> 
>     compile "com.auth0:auth0:1.31.0"
>     compile "com.auth0:jwks-rsa:0.18.0"
> 
>     compile 'com.papertrailapp:logback-syslog4j:1.0.0'
>     compile "com.stripe:stripe-java:20.56.0"
> 
>     compile "com.sendinblue:sib-api-v3-sdk:5.2.0"
> 
>     runtime "org.grails.plugins:async:4.0.0"
>     compile "org.grails:grails-datastore-gorm-async"
> 
>     implementation "com.squareup.okhttp3:okhttp:4.9.0"
>     implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.72'
> 
> }
> 
> bootRun {
>     ignoreExitValue true
>     jvmArgs(
>             '-Dspring.output.ansi.enabled=always',
>             '-noverify',
>             '-XX:TieredStopAtLevel=1',
>             '-Xmx1024m')
>     sourceResources sourceSets.main
>     String springProfilesActive = 'spring.profiles.active'
>     systemProperty springProfilesActive, System.getProperty(springProfilesActive)
> }
> 
> tasks.withType(GroovyCompile) {
>     configure(groovyOptions) {
>         forkOptions.jvmArgs = ['-Xmx1024m']
>     }
> }
> 
> sourceSets {
>     main {
>         resources {
>             srcDir 'grails-app/migrations'
>         }
>     }
> }
> ```
> 
> And the error is:
> ![image](https://user-images.githubusercontent.com/916432/121945098-12bd1900-cd5c-11eb-8c38-ea477789170d.png)

This looks similar to the error we were running into. It's probably because the grails wrapper inside of your repository has the typos. Here are the steps that we took to resolve https://github.com/grails/grails-core/issues/11825#issuecomment-856250177

**Comment by kfujita-cohere** [comment]
> @jeffbrown @puneetbehl
> I updated the repository URLs, as suggested in the workaround and I am still getting the same issue. Like nothing changed.
> Do I need to regenerate the wrapper JAR's somehow to make it work? Or any additional steps to make it work?
> 
> And the error is:
> ![image](https://user-images.githubusercontent.com/916432/121945098-12bd1900-cd5c-11eb-8c38-ea477789170d.png)

 @ShurikAg This looks similar to the error we were running into. It's probably because the grails wrapper inside of your repository has the typos. Here are the steps that we took to resolve https://github.com/grails/grails-core/issues/11825#issuecomment-856250177

**Comment by ShurikAg** [comment]
> > @jeffbrown @puneetbehl
> > I updated the repository URLs, as suggested in the workaround and I am still getting the same issue. Like nothing changed.
> > Do I need to regenerate the wrapper JAR's somehow to make it work? Or any additional steps to make it work?
> > And the error is:
> > ![image](https://user-images.githubusercontent.com/916432/121945098-12bd1900-cd5c-11eb-8c38-ea477789170d.png)
> 
> @ShurikAg This looks similar to the error we were running into. It's probably because the grails wrapper inside of your repository has the typos. Here are the steps that we took to resolve [#11825 (comment)](https://github.com/grails/grails-core/issues/11825#issuecomment-856250177)

Oh wow! Though, I am running Grails 4. Does it make a difference?
Also, any change to get access to that fork? :) Or the generated jar? 😃

**Comment by JasonTypesCodes** [comment]
> Also, any change to get access to that fork? :) Or the generated jar?

@ShurikAg That wrapper error can be resolved by using an updated grails-wrapper.jar.

Please see: https://grails.org/blog/2021-06-10-grails-wrapper-update.html

The issue for this bug is here: https://github.com/grails/grails-wrapper/issues/7

**Comment by JasonTypesCodes** [comment]
I think we can close this issue. If additional problems are encountered, please open a new issue. Thank you.
