### ISSUE TITLE
7.0.0-M1 Command create-app throws Exception

### ISSUE THREAD

**Issue by Tusc0R** [grails/grails-core#14002]
### Expected Behavior

The Command `create-app` should create a new application.

### Actual Behaviour

C:\PRG\grails-7.0.0-M1\bin\grails.bat create-app TestApp --profile=web
Resolving dependencies..
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:web:jar:${profiles-web.version} in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

### Steps To Reproduce

Run 'grails.bat create-app TestApp' with or without a profile switch

### Environment Information

- Windows 11
- Corretto 17.0.14.7.1
- Grails 7.0.0-M1

### Version

7.0.0-M1

**Comment by jamesfredley** [comment]
This was resolved on https://github.com/grails/grails-core/pull/13948

and is working with 7.0.0-SNAPSHOT

clone https://github.com/grails/grails-core
./gradlew assemble
unzip build/distributions/grails-7.0.0-SNAPSHOT.zip
bin/grails

**Comment by weinellucian** [comment]
hi @jamesfredley I had followed the steps and we still see the same issue

**Comment by jamesfredley** [comment]
@weinellucian it looks like you got past the `org.grails.profiles:web:jar:${profiles-web.version}` issue based on https://github.com/grails/grails-core/issues/14026

**Comment by jamesfredley** [comment]
@Tusc0R  https://github.com/grails/grails-profiles/pull/14 has been completed and you can give this another try with the latest grails-core and grails-profiles snapshots.

https://github.com/grails/grails-core/issues/14029 is still open, but has the workaround by shortening the path.

```
clone https://github.com/grails/grails-core
./gradlew assemble
unzip build/distributions/grails-7.0.0-SNAPSHOT.zip
bin/grails
```

**Comment by weinellucian** [comment]
@Tusc0R  we still see this isue on Windows, any suggestions

**Comment by jamesfredley** [comment]
7.0.0-SNAPSHOT has this resolved.  You can grab the updated cli distribution from the last build under artifacts on  https://github.com/apache/grails-forge/actions/runs/15434828384.  This is the new combined CLI which includes grails-shell-cli and grails-forge-cli.  

You can also generate a 7.0.0-SNAPSHOT application on https://start.grails.org

7.0.0-M4 is currently undergoing an ASF vote and if that passes it will be released early next week.

The shell cli has had massive changes in the last month.
