### ISSUE TITLE
Grails 5.3.6 does not work with Tomcat 9.0.99

### ISSUE THREAD

**Issue by akunourshirazivalta** [grails/grails-core#14020]
### Expected Behavior

Grails 5.3.6 does to work with Tomcat 9.0.99

### Actual Behaviour

Grails 5.3.6 does not work with Tomcat 9.0.99

### Steps To Reproduce

1) `sdk use grails 5.3.6`
2) `sdk use java 17.0.14-zulu`
3) `grails create-app myapp`
4) add this line `ext['tomcat.version'] = '9.0.99'` to build.gradle
5)  `./gradlew clean bootRun`

```
2025-02-12 14:50:33.475 ERROR --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:458)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:445)
        at myapp.Application.main(Application.groovy:11)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ExceptionInInitializerError: null
        at org.apache.catalina.startup.Tomcat.<clinit>(Tomcat.java:1216)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:194)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:184)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
        ... 14 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final boolean java.io.FileSystem.useCanonCaches accessible: module java.base does not "opens java.io" to unnamed module @38797004
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.apache.tomcat.util.compat.JreCompat.<clinit>(JreCompat.java:131)
        ... 18 common frames omitted

```
Its most likely do to this commit: [tomcat](https://github.com/apache/tomcat/commit/427732ef8ee7f707a32734a13a926a2d070b8ba9)
see also: https://github.com/advisories/GHSA-27hp-xhwr-wr2m v

### Environment Information

- Linux
- Java 17

### Example Application

https://github.com/akunourshirazivalta/grailstomcaterror

### Version

5.3.6

**Comment by jdaugherty** [comment]
@jamesfredley I believe this is expected and the only option is to upgrade due to later library requirements?

**Comment by jamesfredley** [comment]
@akunourshirazivalta You will most likely need to use Spring Boot 2.7.18 and Spring Framework 5.3.39 to use Tomcat 9.0.99.  The sure way to do this is to upgrade to Grails 6.2.3 and then override those 3 versions.  If you get it to work on Grails 5.3.x please post it here so that others know it can work.

**Comment by akunourshirazivalta** [comment]
Ok, I just tried running Tomcat 9.0.99 on its own with Java 17 and i get the same error. So it might not be a fault with Grails, but rather with Tomcat.

**Comment by akunourshirazivalta** [comment]
Its confirmed it was an error with Tomcat. It has been fixed  with Tomcat 9.0.100

https://tomcat.apache.org/tomcat-9.0-doc/changelog.html 
https://bz.apache.org/bugzilla/show_bug.cgi?id=69576

**Comment by lynchie14** [comment]
@akunourshirazivalta  Can you confirm this works on tomcat 9.0.100 with jdk 17. I've tried myself and used your sample project and it still fails to startup?

**Comment by akunourshirazivalta** [comment]
> [@akunourshirazivalta](https://github.com/akunourshirazivalta) Can you confirm this works on tomcat 9.0.100 with jdk 17. I've tried myself and used your sample project and it still fails to startup?

Yes i have tested it and confirmed it works. Tested with a clean grails project and also with a very simple java 17 project.

Did you remember to changes the tomcat version here: https://github.com/akunourshirazivalta/grailstomcaterror/blob/main/build.gradle#L130

**Comment by lynchie14** [comment]
Are you running on Windows by any chance? Fails to run on windows for me but works under WSL.

**Comment by akunourshirazivalta** [comment]
linux
