### ISSUE TITLE
GORM Domain Objects with Same Field Name

### ISSUE THREAD

**Issue by echopapabravo** [grails/grails-core#9443]
Upgrading from Grails 2.x to 3.x causes an hibernate error on our domain objects which have an unique field with same field name. 

Reproduced please see: [/echopapabravo/gorm-domain-objects-unique-same-field-name](https://github.com/echopapabravo/gorm-domain-objects-unique-same-field-name)

**Comment by graemerocher** [comment]
I believe this is fixed in the 5.0.0.RC1 version of the `hibernate4` plugin

**Comment by echopapabravo** [comment]
I tried with version `org.grails.plugins:hibernate4:5.0.0.RC1`. Same issue, didn't solve the problem. 
I pushed the change to https://github.com/echopapabravo/gorm-domain-objects-unique-same-field-name

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/issues/623
